---
- name: GATHER INFORMATION FROM ROUTERS
  hosts: cisco
  connection: network_cli
  gather_facts: no

  tasks:
    - name: GATHER ROUTER FACTS
      ios_facts:
      tags: facts

    - name: SHOW VERSION
      debug:
        msg: "{{ ansible_net_version }}"
      tags: facts

    - name: SHOW SERIAL NUMBER
      debug:
        msg: "{{ ansible_net_serialnum }}"
      tags: facts

    - name: SHOW COMMANDS
      ios_command:
        commands:
          - show run | i hostname
          - show ip int br
      register: show_output
      tags: show

    - debug:
        msg: "{{ show_output }}"
      tags: show

    - debug:
        msg: "{{ show_output.stdout[0]}}"
      tags: show
