---
- name: RESTORE CONFIGURATION
  hosts: routers
  connection: network_cli
  gather_facts: no

  tasks:
    - name: whoami
      command: whoami
      register: whoami

    - debug:
        msg: "{{whoami}}"

    - name: COPY RUNNING CONFIG TO ROUTER
      command: scp -i /home/ec2-user/.ssh/aws-private.pem ./backup/{{inventory_hostname}}.config ec2-user@{{inventory_hostname}}:/{{inventory_hostname}}.config
      tags: scp

    - name: CONFIG REPLACE
      ios_command:
        commands:
          - config replace flash:{{inventory_hostname}}.config force
