---
- name: Dynamic Reporting
  hosts: routers
  gather_facts: no
  connection: network_cli

  roles:
    - ansible-network.network-engine

  tasks:
  - name: Capture show interfaces
    ios_command:
      commands:
        - show interfaces
    register: output

  - name: "command_parser test for {{ ansible_network_os }} show_interface"
    command_parser:
      file: "parsers/show_interfaces.yaml"
      content: "{{ output.stdout[0] }}"
    register: result


  - name: Generate Interfaces Report
    template:
      src: templates/interface_facts.j2
      dest: reports/{{inventory_hostname}}-interfaces.md
