---
- name: RESET ROUTER CONFIGURATIONS
  hosts: routers
  connection: network_cli
  gather_facts: no

  vars:
    site_domain_name: 'example.net'
    network_name_servers:
      - 8.8.8.8
      - 8.8.4.4
    network_domain_search:
      - example.net

  tasks:
    - name: REMOVE THE HOSTNAME AND DOMAIN NAME
      net_system:
        domain_name: "{{ site_domain_name }}"
        domain_search: "{{ network_domain_search | default(omit) }}"
        name_servers: "{{ network_name_servers | default(omit) }}"
        state: absent
