---
- name: RESET ROUTER CONFIGURATIONS
  hosts: routers
  connection: network_cli
  gather_facts: no

  vars:
    site_domain_name: 'example.net'
    network_name_servers:
      - 8.8.8.8
      - 8.8.4.4
    network_domain_search:
      - example.net

  tasks:
    - name: REMOVE THE HOSTNAME AND DOMAIN NAME
      net_system:
        domain_name: "{{ site_domain_name }}"
        domain_search: "{{ network_domain_search | default(omit) }}"
        name_servers: "{{ network_name_servers | default(omit) }}"
        state: absent

    - name: ADD HOSTNAME
      ios_config:
        commands:
          - hostname {{ inventory_hostname }}
          - no banner login
          - no banner motd
          - no ip domain list example.net
          - no ip domain name example.net
          - no snmp-server community ansible-public RO
          - no snmp-server community ansible-private RW
          - no ip ssh authentication-retries 5
          - no service password-encryption
          - no service tcp-keepalives-in
          - no service tcp-keepalives-out
          - ip http server
    - ios_config:
        parents: line con 0
        lines:
          - no exec-timeout 5 0

    - ios_config:
        parents: line vty 0 4
        lines:
          - no exec-timeout 5 0
